import '../stylesheets/LoadSpinner.css'
export default function LoadSpinner() {
  return (
    <>
      <div className='d-flex justify-content-center align-self-center mx-auto'>
        <div className='loadingio-spinner-spinner-94sumfx7kxi'>
          {/* generated by https://loading.io/  */}
          <div className='ldio-cs9r5gg8z0w'>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        </div>
      </div>
    </>
  )
}
